apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    uses: gmaxey/reusableworkflows/MyAppBuild.yaml
    with:
      artifactName: MyAppFEaaa
      baseVersion: 3.1.4
      digest: sha256:aaafe313aaa123abcdef===
