apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build
on:
  push:
    branches:
      - "**"
jobs:
  build:
    uses: gmaxey/reusableworkflows/MyAppBuild.yaml
    with:
      artifactName: MyAppFE
      baseVersion: 3.1.5
      digest: sha256:fe315aaa123abcdef===
      labels: built
