apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: deploy
on:
  workflow_dispatch:
    inputs:
      artifactName:
        type: string
        required: true
      artifactVersion:
        type: string
        required: true
      environment:
        type: string
        required: true
      url:
        type: string
        required: false
      digest:
        type: string
        required: false
jobs:
  pre-prod:
    uses: gmaxey/reusableworkflows/MyAppDeploy.yaml
    with:
      artifactName:     ${{ inputs.artifactName }}
      artifactVersion:  ${{ inputs.artifactVersion }}
      environment:      ${{ inputs.environment }}
      url:              ${{ inputs.url }}
      digest:           ${{ inputs.digest }}